# source https://github.com/actions/labeler/blob/master/README.md
# Add 'repo' label to any root file changes
Porn:
  - submit_here/hosts.txt

NSFW Adult Material:
  - submit_here/hosts.txt

Snuff:
  - submit_here/snuff.txt

Whitelist:
  - submit_here/whitelist.txt

# Add '@domain/core' label to any change within the 'core' package
#@domain/core:
#  - package/core/*
#  - package/core/**/*

# Add 'test' label to any change to *.spec.js files within the source dir
#test:
#  - src/**/*.spec.js
