dist: bionic
language: python
python:
- '3.8'
cache:
  pip: true
  directories:
  - "$HOME/db/"
env:
  global:
  - GIT_NAME: Spirillen
  - GIT_EMAIL: 44526987+spirillen@users.noreply.github.com
  - TRAVIS_REPO_SLUG: Import-External-Sources/pornhosts
  - GIT_BRANCH: master
  - TZ: UTC
  - PYFUNCEBLE_CONFIG_DIR: "${TRAVIS_BUILD_DIR}/dev-tools/"
  - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble
  - DEBUG_PYFUNCEBLE_ON_SCREEN: true
  - secure: CRu8TgXoJ2CDUIux4Li4T9hnKshvPTffRZdtmgOYHIUW5/ARpZnUP2yHuYY+MSLJBDoVwO9KsT5qqHVev0ki8wvxlT95XhEkaRsh1KWuKXj/q5TRoeOexR0kicC8a8sSlxuLxVVR4E9DNpzbsG0HZRFgk9eduQILkcaYqpqw/DiqpCvzH1RzPtBXbKwjU9z6O9QLvG3I/6eNP2boIT5XZSuKporfAJHe7adhMJPCuUpmLOGzMr3xurvbMWMtCjpTBoYUZp1nN6e4iMy/AigRvzgu68tXnnJV0QBAm3sAbs3+nl/DfgtLhK945Do9o/uDz7C25lmnJMi6ZDg3YUDmc0ZVfmNHA5hGv8AwIKohMvfJw7ypFeqDWppxO/30k3T3KaS/vbVfYANSFm6ttcoI1SXXCqCePoh+Qcw4AEuucgZUCLwliVxFbjQaWvV6m7yQorUhABVWIjOtEQqkqCNl8QJI3bwL8yhg41Wo7ktXOF0GA1Rr48G27PZvuxEHLwZe72LJBxXZDEU7JUUff7HoNufc7nIzilDO0Xf6bBHFPvhHVjHyEcgMW2H/1WUmEkv6G7oGXicnwDngbyo4mJDv+YH1YYIlN+MdgaIRm+eEYLX5kVTQlZL2l7BySAc/ltAk16yfcxBI4wpl1MVsXNgY+2SaJIgd36LUt6bd1lamLEo=
addons:
  mariadb: '10.4'
  apt:
    packages:
    - dos2unix
    - msttcorefonts
    - lsof
    - pdns-recursor
install:
- pip3 install --upgrade pip
- pip3 install git+https://github.com/funilrys/PyFunceble.git@dev
git:
  depth: 2
branches:
  only:
  - master
  - pyfunceble-processing
matrix:
  fast_finish: true
sudo: required
script:
- sudo systemctl restart mysql.service
- sudo mysql -u root -h localhost -e "CREATE DATABASE pyfunceble DEFAULT CHARACTER
  SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
- sudo mysql -u root -h localhost -e "CREATE USER 'root'@'%' IDENTIFIED BY ''"
- sudo mysql -u root -h localhost -e "CREATE USER 'pyfunceble'@'localhost' IDENTIFIED
  BY 'pyfunceble';"
- sudo mysql -u root -h localhost -e "GRANT ALL PRIVILEGES ON pyfunceble.* TO 'pyfunceble'@'localhost';"
- sudo mysql --user=pyfunceble --password=pyfunceble pyfunceble < ${HOME}/db/pyfunceble.sql
- bash dev-tools/PrepareData.sh && bash dev-tools/DataTesting.sh && sudo mkdir -p
  ${HOME}/db/ && sudo mysqldump --user=pyfunceble --password=pyfunceble --opt pyfunceble
  > ${HOME}/db/pyfunceble.sql
