blank_issues_enabled: false
contact_links:
  - name: My Privacy DNS Community Support
    url: https://www.mypdns.org/maniphest/
    about: Please ask and answer questions here.
  - name: DNS Firewall about Adult contents
    url: https://github.com/Import-External-Sources/pornhosts
    about: Please report adult contents here.
  - name: DNS Firewall through RPZ zone
    url: https://www.mypdns.org/w/rpzlist/
    about: Please read intro for all our Response Policy Zones for DNS Firewalls
